# Generated by Django 4.2.5 on 2023-09-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
