# Generated by Django 5.0 on 2023-12-15 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_productos_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='category_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='categorias',
            table='',
        ),
        migrations.AlterModelTable(
            name='productos',
            table='',
        ),
    ]
