# Generated by Django 5.0 on 2024-01-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_rename_category_name_categorias_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='img_inventario'),
        ),
    ]
